### ISSUE TITLE
Hi-score Update problems

### ISSUE THREAD

**Issue by Cubitus75** [GreatStoneEx/hi2txt-xml#24]
Randomly, whenever i beat a hi-score, it's not updated. 
According to Jason Carr, regarding the log files i submitted, it's a Hi2txt problem.
Here are 2 log files i submitted, but it happens randomly on random games....

[Debug 2020-05-05 10-30-07 PM.log](https://github.com/GreatStoneEx/hi2txt-xml/files/4588940/Debug.2020-05-05.10-30-07.PM.log)
[Debug 2020-05-05 06-37-21 PM.log](https://github.com/GreatStoneEx/hi2txt-xml/files/4588941/Debug.2020-05-05.06-37-21.PM.log)

**Comment by GreatStoneEx** [comment]
5 possible cases :)

   1. if the log file shows that LaunchBox does not detect nvram nor .hi files saved by mame with the scores, it is a mame emulation or hiscore plugin issue: this hiscore saving system is not 100% accurate. nothing hi2txt utility can do here (it is just decoding what is saved)

   2. if the log file shows a message like "WRONG SCORE value", it means that mame emulation or hiscore plugin has saved corrupted data in the nvram or .hi file: this hiscore saving system is not 100% accurate. nothing hi2txt utility can do here (it is just decoding what is saved)

   3. if the log file shows that LaunchBox does detect nvram/hi files, is calling hi2txt, hi2txt displays hiscores but not your new hiscores, back to case 1: hiscores not saved by mame.

   4. if the log file shows that LaunchBox does detect nvram/hi files, is calling hi2txt, hi2txt displays no scores: hi2txt filters hiscores for some games if values = 0 and do not display them. Back to case 1: hiscores not saved by mame.

   5. only 30% of the mame games are currently supported by hi2txt: if the log file shows the 
message "No XML description found", the game is not yet supported and any contribution is welcome to provide an XML to decode it :) In this case, it is not random but systematic for the game.

Analysis for provided logs
=========    
1st log with "airass" is in case 3.
2nd log for "altair" is in case 2.
Nothing hi2txt can do in these cases.

Anyway, thanks a lot for the time taken to report it: it will help it to be more robust.
