### ISSUE TITLE
Cyber-Lip saveram file not decoding properly

### ISSUE THREAD

**Issue by edgespresso** [GreatStoneEx/hi2txt-xml#29]
- Mame 0.220 creates both a cyberlip.hi and a cyberlip/saveram file.
- Hi2Txt cyberlip.xml only defines the hiscore logic for saveram. 
- Hi2Txt reads the saveram file, but exports a default hiscore table which is not correct.  I have hiscores set (and can see it when running the game), but they are not extracted.  See example output below.

```
<hi2txt>
  <table>
    <col>RANK</col><col>SCORE</col><col>NAME</col>
    <row><cell>1</cell><cell>100000</cell><cell>SNK</cell></row>
    <row><cell>2</cell><cell>90000</cell><cell>SNK</cell></row>
    <row><cell>3</cell><cell>80000</cell><cell>SNK</cell></row>
    <row><cell>4</cell><cell>70000</cell><cell>SNK</cell></row>
    <row><cell>5</cell><cell>60000</cell><cell>SNK</cell></row>
    <row><cell>6</cell><cell>50000</cell><cell>SNK</cell></row>
    <row><cell>7</cell><cell>40000</cell><cell>SNK</cell></row>
    <row><cell>8</cell><cell>30000</cell><cell>SNK</cell></row>
    <row><cell>9</cell><cell>20000</cell><cell>SNK</cell></row>
    <row><cell>10</cell><cell>10000</cell><cell>SNK</cell></row>
  </table>
</hi2txt>
```
Thanks for your help!

**Comment by GreatStoneEx** [comment]
Great report, really helping to debug it 👍

**Comment by GreatStoneEx** [comment]
Tested with mame 0.229, and the saveram file is indeed storing the new score:
```
<hi2txt>
  <table>
    <col>RANK</col><col>SCORE</col><col>NAME</col>
    <row><cell>1</cell><cell>100000</cell><cell>SNK</cell></row>
    <row><cell>2</cell><cell>90000</cell><cell>SNK</cell></row>
    <row><cell>3</cell><cell>80000</cell><cell>SNK</cell></row>
    <row><cell>4</cell><cell>70000</cell><cell>SNK</cell></row>
    <row><cell>5</cell><cell>60000</cell><cell>SNK</cell></row>
    <row><cell>6</cell><cell>50000</cell><cell>SNK</cell></row>
    <row><cell>7</cell><cell>40000</cell><cell>SNK</cell></row>
    <row><cell>8</cell><cell>30000</cell><cell>SNK</cell></row>
    <row><cell>9</cell><cell>24100</cell><cell>C!&amp;</cell></row>
    <row><cell>10</cell><cell>20000</cell><cell>SNK</cell></row>
  </table>
</hi2txt>
```
See the score number 9 with a new score, new name.
I will dig now with mame 0.220 specifically.

@edgespresso do you have the opportunity to test with another mame version?

**Comment by GreatStoneEx** [comment]
Same for 0.220 with my config: saveram is storing the new score...
I will nevertheless tried to decode hi file also additionally to saveram, to cover your use-case.

**Comment by GreatStoneEx** [comment]
@edgespresso I pushed a new xml for cyberlip, decoding also .hi file: can you test it on your side to see if your issue is solved now?
